<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Nordic Soft Velvet Sofa',
                'slug' => 'nordic-soft-velvet-sofa',
                'category' => 'Living Room',
                'price' => 8490000,
                'original_price' => 9990000,
                'rating' => 4.9,
                'review_count' => 38,
                'description' => 'Sofa minimalis bergaya Scandinavia dengan balutan kain velvet ultra-soft dan rangka kayu mahoni solid. Dirancang ergonomis untuk kenyamanan maksimal saat bersantai bersama keluarga.',
                'dimensions' => '210 cm x 90 cm x 82 cm',
                'material' => 'Kain Velvet Impor & Rangka Kayu Mahoni Solid',
                'image_url' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_new' => true,
                'stock' => 8,
            ],
            [
                'name' => 'Artisan Teak Dining Table',
                'slug' => 'artisan-teak-dining-table',
                'category' => 'Dining Room',
                'price' => 12500000,
                'original_price' => 14200000,
                'rating' => 4.8,
                'review_count' => 24,
                'description' => 'Meja makan kayu jati Jepara premium berkapasitas 6-8 orang dengan finishing alami matte oil. Menampilkan serat kayu jati autentik yang memukau dan tahan hingga puluhan tahun.',
                'dimensions' => '200 cm x 100 cm x 76 cm',
                'material' => '100% Kayu Jati TPK Grade A',
                'image_url' => 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_new' => false,
                'stock' => 5,
            ],
            [
                'name' => 'Minimalist Lounge Armchair',
                'slug' => 'minimalist-lounge-armchair',
                'category' => 'Living Room',
                'price' => 3850000,
                'original_price' => 4500000,
                'rating' => 4.7,
                'review_count' => 52,
                'description' => 'Kursi santai modern dengan bantalan empuk berlapis kulit sintetis premium dan kaki besi kokoh berlapis matte black powder coating.',
                'dimensions' => '85 cm x 80 cm x 78 cm',
                'material' => 'Leatherette Premium & Steel Legs',
                'image_url' => 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_new' => true,
                'stock' => 12,
            ],
            [
                'name' => 'Kyoto Platform Bed Frame',
                'slug' => 'kyoto-platform-bed-frame',
                'category' => 'Bedroom',
                'price' => 9750000,
                'original_price' => 11000000,
                'rating' => 4.9,
                'review_count' => 41,
                'description' => 'Ranjang tempat tidur gaya Japandi berbahan kayu oak utuh dengan headboard terintegrasi & lampu LED warm ambient tersembunyi.',
                'dimensions' => '180 cm x 200 cm (King Size)',
                'material' => 'Solid Oak Wood & Integrated Ambient Lighting',
                'image_url' => 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_new' => true,
                'stock' => 6,
            ],
            [
                'name' => 'Ergonomic Executive Office Chair',
                'slug' => 'ergonomic-executive-office-chair',
                'category' => 'Office',
                'price' => 4200000,
                'original_price' => 4900000,
                'rating' => 4.8,
                'review_count' => 67,
                'description' => 'Kursi kerja ergonomis tingkat tinggi dengan penopang lumbal yang dapat disesuaikan, bahan mesh high-density, dan mekanisme reclining 135 derajat.',
                'dimensions' => '68 cm x 65 cm x 115-125 cm',
                'material' => 'Breathable Korean Mesh & Aluminum Alloy Base',
                'image_url' => 'https://images.unsplash.com/photo-1580481072645-022f9a6d8310?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_new' => false,
                'stock' => 15,
            ],
            [
                'name' => 'Aura Rattan Outdoor Sofa Set',
                'slug' => 'aura-rattan-outdoor-sofa-set',
                'category' => 'Outdoor',
                'price' => 14800000,
                'original_price' => 16500000,
                'rating' => 4.9,
                'review_count' => 19,
                'description' => 'Set sofa outdoor berbahan rotan sintetis weatherproof tahan panas & hujan. Dilengkapi bantalan busa quick-dry dan meja kaca tempered 8mm.',
                'dimensions' => 'Set 4 Pcs (Sofa 3-seater, 2 Single Armchair, Meja Coffee)',
                'material' => 'Synthetic PE Rattan & Aluminum Frame',
                'image_url' => 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_new' => false,
                'stock' => 4,
            ],
            [
                'name' => 'Modena Modern Nightstand',
                'slug' => 'modena-modern-nightstand',
                'category' => 'Bedroom',
                'price' => 1950000,
                'original_price' => 2300000,
                'rating' => 4.6,
                'review_count' => 33,
                'description' => 'Meja samping tempat tidur dengan 2 laci push-to-open yang halus dan aksen rangka kuningan yang mewah.',
                'dimensions' => '50 cm x 40 cm x 55 cm',
                'material' => 'MDF Finished Walnut Veneer & Brass Handles',
                'image_url' => 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_new' => true,
                'stock' => 20,
            ],
            [
                'name' => 'Solace Wooden Study Desk',
                'slug' => 'solace-wooden-study-desk',
                'category' => 'Office',
                'price' => 5100000,
                'original_price' => 5800000,
                'rating' => 4.7,
                'review_count' => 29,
                'description' => 'Meja kerja/belajar minimalis berdesain clean dengan pengatur kabel tersembunyi dan kompartemen laci ganda.',
                'dimensions' => '140 cm x 65 cm x 75 cm',
                'material' => 'Solid Ash Wood',
                'image_url' => 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_new' => false,
                'stock' => 10,
            ],
            [
                'name' => 'Verona Marble Top Coffee Table',
                'slug' => 'verona-marble-top-coffee-table',
                'category' => 'Living Room',
                'price' => 4750000,
                'original_price' => 5500000,
                'rating' => 4.8,
                'review_count' => 45,
                'description' => 'Meja kopi bundar bertop marmer Carrara asli dengan urat marmer elegan, ditopang oleh struktur kaki baja berlapis aksen emas mawar.',
                'dimensions' => '80 cm x 80 cm x 45 cm',
                'material' => 'Carrara Italian Marble & Rose Gold Steel',
                'image_url' => 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_new' => true,
                'stock' => 7,
            ],
            [
                'name' => 'Soren Minimalist Bookshelf',
                'slug' => 'soren-minimalist-bookshelf',
                'category' => 'Office',
                'price' => 3450000,
                'original_price' => 3990000,
                'rating' => 4.6,
                'review_count' => 21,
                'description' => 'Rak buku bertingkat 5 berkonsep terbuka yang estetis. Cocok untuk menaruh koleksi buku favorit, tanaman hias, dan barang dekorasi rumah.',
                'dimensions' => '90 cm x 35 cm x 180 cm',
                'material' => 'Natural Birch Plywood & Matte Metal Support',
                'image_url' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_new' => false,
                'stock' => 14,
            ],
            [
                'name' => 'Luxe Velvet Dining Chair Set',
                'slug' => 'luxe-velvet-dining-chair-set',
                'category' => 'Dining Room',
                'price' => 4950000,
                'original_price' => 5800000,
                'rating' => 4.9,
                'review_count' => 36,
                'description' => 'Set 2 kursi makan mewah berlapis kain velvet dengan jahitan quilted berlian dan kaki kayu walnut yang kokoh & nyaman.',
                'dimensions' => '52 cm x 58 cm x 88 cm (Per Kursi)',
                'material' => 'Premium Soft Velvet & Solid Walnut Legs',
                'image_url' => 'https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_new' => true,
                'stock' => 9,
            ],
            [
                'name' => 'Zenith Outdoor Sun Lounger',
                'slug' => 'zenith-outdoor-sun-lounger',
                'category' => 'Outdoor',
                'price' => 3950000,
                'original_price' => 4600000,
                'rating' => 4.7,
                'review_count' => 16,
                'description' => 'Kursi jemur/berjemur outdoor tepi kolam renang dengan sandaran yang dapat disesuaikan 4 posisi dan bahan kain textilene tahan sinar UV.',
                'dimensions' => '195 cm x 70 cm x 35 cm',
                'material' => 'Weatherproof Aluminum & UV-Resistant Fabric',
                'image_url' => 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_new' => false,
                'stock' => 11,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['slug' => $product['slug']], $product);
        }
    }
}
